name: 'DB migration with DLE'
description: 'Run DB migrations with the DLE'
inputs:
  owner:
    description: 'The owner of the repository to check'
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: 'The repo to check'
    required: true
    default: ${{ github.event.repository.name }}
  ref:
    description: 'The input represents a ref parameter, which can be a SHA, branch, or tag'
    required: true
    default: ${{ github.ref }}
  pull_request:
    description: 'Link to the pull request'
    required: false
    default: ${{ github._link.html.href }}
  diff:
    description: 'Compare'
    required: false
    default: ${{ github.event.compare }}
  commands:
    description: 'List of commands to run DB migrations'
    required: true
  dbname:
    description: 'The database that the workflow is running with'
    required: false
    default: ""
  migration_envs:
    description: 'List of commands to run DB migrations'
    required: false
outputs:
  response:
    description: 'The result of CI checks'
runs:
  using: 'docker'
  image: 'Dockerfile'
